name: 'Build and Test'

on:
    workflow_dispatch:
    pull_request:

jobs:
    build:
        name: Build git-changesets
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                  yarn
                  yarn build
    test:
        name: Test git-changesets
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - run: |
                  yarn
                  yarn test
