name: 'Build and Test'

on:
    pull_request:
        branches:
            - master

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Commitlint
              uses: wagoid/commitlint-github-action@v4
              with:
                  failOnWarnings: true

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install Dependencies
              run: yarn

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test

    RunAction:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - id: files
              name: Run the action
              uses: ./

            - name: Print steps context output
              run: |
                  echo 'steps.files.outputs.all=${{ steps.files.outputs.all }}'
                  echo 'steps.files.outputs.added=${{ steps.files.outputs.added }}'
                  echo 'steps.files.outputs.modified=${{ steps.files.outputs.modified }}'
                  echo 'steps.files.outputs.removed=${{ steps.files.outputs.removed }}'
                  echo 'steps.files.outputs.renamed=${{ steps.files.outputs.renamed }}'
                  echo 'steps.files.outputs.added_modified=${{ steps.files.outputs.added_modified }}'
