name: 'Execute git-changesets built JavaScript'

on:
    pull_request:

jobs:
    test:
        name: Execute built JavaScript
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - id: files
              name: Run the action
              uses: ./

            - name: Print steps context output
              run: |
                  echo 'steps.files.outputs.all=${{ steps.files.outputs.all }}'
                  echo 'steps.files.outputs.added=${{ steps.files.outputs.added }}'
                  echo 'steps.files.outputs.modified=${{ steps.files.outputs.modified }}'
                  echo 'steps.files.outputs.removed=${{ steps.files.outputs.removed }}'
                  echo 'steps.files.outputs.renamed=${{ steps.files.outputs.renamed }}'
                  echo 'steps.files.outputs.added_modified=${{ steps.files.outputs.added_modified }}'
